CREATE SCHEMA IF NOT EXISTS my_db.timeline_reconciliation;

-- ============================================================
-- 1. Classified timeline tasks staging
-- ============================================================

CREATE TABLE IF NOT EXISTS my_db.timeline_reconciliation.TimelineTasksClassified (
    TimelineName VARCHAR,
    ProjectCode VARCHAR,

    TaskRowId BIGINT,
    TaskCode VARCHAR,
    TaskName VARCHAR,
    WbsName VARCHAR,
    TaskText VARCHAR,

    TaskClass VARCHAR,
    TaskClassConfidence VARCHAR,
    TaskClassReason VARCHAR,
    ClassifierModel VARCHAR,
    ClassifierPromptVersion VARCHAR,

    CreatedAt TIMESTAMP DEFAULT NOW(),
    UpdatedAt TIMESTAMP DEFAULT NOW(),
    CreatedBy VARCHAR
);

COMMENT ON TABLE my_db.timeline_reconciliation.TimelineTasksClassified IS
'Staging table for Primavera timeline task classification. Contains one row per source timeline task and stores the LLM classification ENG_DOC or OTHER before any MDR association is attempted. This is the canonical input table for downstream timeline-to-MDR reconciliation steps.';

COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TimelineName IS
'Name of the source Primavera timeline, normally derived from the input XLSX filename. Expected to match historical MDR Mdr_code_name_ref for project filtering.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.ProjectCode IS
'Project code extracted from TimelineName, for example 7910 from "7910 - TAP Greece Kipoi". Useful for reporting but not the preferred MDR join key.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskRowId IS
'Original row index of the task in the Primavera TASK sheet. Together with TimelineName identifies the source task.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskCode IS
'Primavera activity/task code when available in the TASK sheet.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskName IS
'Original Primavera task/activity name from the TASK sheet.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.WbsName IS
'Resolved WBS name joined from PROJWBS using wbs_id when available. Used as context for classification and task-to-MDR matching.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskText IS
'Prepared text used for downstream semantic matching, typically combining TaskName, WbsName, and TaskClass.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskClass IS
'Task classification. Expected values: ENG_DOC for engineering document progress tasks, OTHER for tasks not directly linkable to MDR/RACI documents.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskClassConfidence IS
'Classifier confidence for TaskClass. Expected values: HIGH, MEDIUM, LOW.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.TaskClassReason IS
'Short explanation of the task classification, generated by the classifier/LLM.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.ClassifierModel IS
'Model used to classify the task, for example gpt-4o-mini.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.ClassifierPromptVersion IS
'Version identifier for the classification prompt or logic.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.CreatedAt IS
'Timestamp when this staging row was inserted.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.UpdatedAt IS
'Timestamp when this staging row was last refreshed.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTasksClassified.CreatedBy IS
'Script or process that created/refreshed this row.';

-- ============================================================
-- 2. Embeddings for ENG_DOC timeline tasks
-- ============================================================

CREATE TABLE IF NOT EXISTS my_db.timeline_reconciliation.TimelineTaskEmbeddings (
    TimelineName VARCHAR,
    ProjectCode VARCHAR,

    TaskRowId BIGINT,
    TaskText VARCHAR,
    EmbeddingModel VARCHAR,
    TextHash VARCHAR,
    Embedding BLOB,
    Dim INTEGER,

    CreatedAt TIMESTAMP DEFAULT NOW(),
    UpdatedAt TIMESTAMP DEFAULT NOW(),
    CreatedBy VARCHAR
);

COMMENT ON TABLE my_db.timeline_reconciliation.TimelineTaskEmbeddings IS
'Stored embeddings for timeline tasks classified as ENG_DOC. These vectors are used to retrieve semantically similar MDR candidates within the same TimelineName.';

COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.TimelineName IS
'Timeline identifier inherited from TimelineTasksClassified.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.ProjectCode IS
'Project code extracted from TimelineName.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.TaskRowId IS
'Original task row id. Joins back to TimelineTasksClassified using (TimelineName, TaskRowId).';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.TaskText IS
'Exact text embedded for the ENG_DOC task, typically task name plus WBS context.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.EmbeddingModel IS
'Embedding model used to generate the vector.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.TextHash IS
'Hash of TaskText used to detect whether the embedding must be refreshed.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.Embedding IS
'L2-normalized embedding vector stored as float32 bytes.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.Dim IS
'Embedding vector dimension.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.CreatedAt IS
'Timestamp when the embedding row was inserted.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.UpdatedAt IS
'Timestamp when the embedding was last refreshed.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskEmbeddings.CreatedBy IS
'Script or process that generated this embedding.';

-- ============================================================
-- 3. Embeddings for MDR candidates already consolidated as RACI MATCH
-- ============================================================

CREATE TABLE IF NOT EXISTS my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings (
    TimelineName VARCHAR,
    ProjectCode VARCHAR,

    MdrDocumentTitle VARCHAR,
    MdrTitleKey VARCHAR,

    ConsolidatedDecisionType VARCHAR,
    ConsolidatedTitleKey VARCHAR,
    ConsolidatedRaciTitle VARCHAR,
    ConsolidatedConfidence DOUBLE,
    ConsolidatedReason VARCHAR,
    ConsolidatedSource VARCHAR,

    EffectiveDescription VARCHAR,
    DisciplineName VARCHAR,
    TypeName VARCHAR,
    CategoryDescription VARCHAR,
    ChapterName VARCHAR,
    CandidateText VARCHAR,

    EmbeddingModel VARCHAR,
    TextHash VARCHAR,
    Embedding BLOB,
    Dim INTEGER,

    CreatedAt TIMESTAMP DEFAULT NOW(),
    UpdatedAt TIMESTAMP DEFAULT NOW(),
    CreatedBy VARCHAR
);

COMMENT ON TABLE my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings IS
'Stored embeddings for MDR document candidates that belong to a TimelineName and already have ConsolidatedDecisionType = MATCH in mdr_reconciliation.v_MdrReconciliationResults_Consolidated. CandidateText combines MDR title, consolidated RACI title, final RACI description, and RACI metadata.';

COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.TimelineName IS
'Timeline/project identifier matched exactly to historical MDR Mdr_code_name_ref.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ProjectCode IS
'Project code extracted from TimelineName.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.MdrDocumentTitle IS
'Historical MDR document title from v_MdrPreviousRecords_Normalized_All.Document_title.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.MdrTitleKey IS
'Normalized key for the MDR document title, typically lower(trim(MdrDocumentTitle)).';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ConsolidatedDecisionType IS
'Final MDR-to-RACI business decision type. This table should normally contain only MATCH rows.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ConsolidatedTitleKey IS
'Final RACI TitleKey selected by the consolidated MDR-to-RACI reconciliation view.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ConsolidatedRaciTitle IS
'Final RACI title selected by the consolidated MDR-to-RACI reconciliation view.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ConsolidatedConfidence IS
'Final confidence from the consolidated MDR-to-RACI reconciliation result.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ConsolidatedReason IS
'Final reason from the consolidated MDR-to-RACI reconciliation result.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ConsolidatedSource IS
'Source layer of the consolidated result, for example judge_3_3 or recovery_3_4.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.EffectiveDescription IS
'Effective RACI document description, manual override preferred when available, used as semantic context for candidate matching.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.DisciplineName IS
'Human-readable RACI discipline name for the consolidated RACI document.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.TypeName IS
'Human-readable RACI document type name.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.CategoryDescription IS
'Human-readable RACI category description.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.ChapterName IS
'Human-readable RACI chapter name.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.CandidateText IS
'Exact text embedded for timeline-to-MDR retrieval, combining MDR title and RACI semantic context.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.EmbeddingModel IS
'Embedding model used to generate the vector.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.TextHash IS
'Hash of CandidateText used to detect whether the embedding must be refreshed.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.Embedding IS
'L2-normalized embedding vector stored as float32 bytes.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.Dim IS
'Embedding vector dimension.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.CreatedAt IS
'Timestamp when the candidate embedding row was inserted.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.UpdatedAt IS
'Timestamp when the candidate embedding was last refreshed.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineMdrCandidateEmbeddings.CreatedBy IS
'Script or process that generated this candidate embedding.';

-- ============================================================
-- 4. Semantic retrieval Top-K: timeline task -> MDR candidate
-- ============================================================

CREATE TABLE IF NOT EXISTS my_db.timeline_reconciliation.TimelineTaskToMdrCandidates (
    TimelineName VARCHAR,
    ProjectCode VARCHAR,

    TaskRowId BIGINT,
    TaskName VARCHAR,
    WbsName VARCHAR,

    MdrDocumentTitle VARCHAR,
    MdrTitleKey VARCHAR,
    ConsolidatedTitleKey VARCHAR,
    ConsolidatedRaciTitle VARCHAR,

    Similarity DOUBLE,
    Rank INTEGER,
    EmbeddingModel VARCHAR,
    RetrievalMethod VARCHAR,
    TaskTextHash VARCHAR,
    CandidateTextHash VARCHAR,

    CreatedAt TIMESTAMP DEFAULT NOW(),
    CreatedBy VARCHAR
);

COMMENT ON TABLE my_db.timeline_reconciliation.TimelineTaskToMdrCandidates IS
'Top-K semantic retrieval candidates from ENG_DOC timeline tasks to MDR documents already consolidated as RACI MATCH. This table is evidence only: Similarity and Rank are retrieval signals, not final business truth.';

COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.TimelineName IS
'Timeline/project identifier. Retrieval is performed only within the same TimelineName.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.ProjectCode IS
'Project code extracted from TimelineName.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.TaskRowId IS
'Original task row id from TimelineTasksClassified.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.TaskName IS
'Original Primavera task name for audit and prompt context.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.WbsName IS
'Resolved WBS name for audit and prompt context.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.MdrDocumentTitle IS
'Candidate MDR document title retrieved for the ENG_DOC task.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.MdrTitleKey IS
'Normalized key for the candidate MDR title.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.ConsolidatedTitleKey IS
'Final RACI TitleKey associated with this MDR candidate.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.ConsolidatedRaciTitle IS
'Final RACI title associated with this MDR candidate.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.Similarity IS
'Cosine similarity between the ENG_DOC task embedding and the MDR candidate embedding.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.Rank IS
'Rank of the candidate within the Top-K retrieval set for the same (TimelineName, TaskRowId). Rank 1 is most similar.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.EmbeddingModel IS
'Embedding model used for both task and candidate vectors.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.RetrievalMethod IS
'Retrieval method identifier, for example embedding_cosine_topk.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.TaskTextHash IS
'Hash of the embedded task text used for traceability to TimelineTaskEmbeddings.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.CandidateTextHash IS
'Hash of the embedded candidate text used for traceability to TimelineMdrCandidateEmbeddings.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.CreatedAt IS
'Timestamp when this retrieval candidate row was inserted.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrCandidates.CreatedBy IS
'Script or process that generated the retrieval candidate row.';

-- ============================================================
-- 5. Final business links: timeline task -> MDR -> RACI
-- ============================================================

CREATE TABLE IF NOT EXISTS my_db.timeline_reconciliation.TimelineTaskToMdrLinks (
    TimelineName VARCHAR,
    ProjectCode VARCHAR,

    TaskRowId BIGINT,
    TaskCode VARCHAR,
    TaskName VARCHAR,
    WbsName VARCHAR,

    TaskClass VARCHAR,
    TaskClassConfidence VARCHAR,
    TaskClassReason VARCHAR,

    MdrDocumentTitle VARCHAR,
    MdrTitleKey VARCHAR,

    LinkRank INTEGER,
    LinkScore DOUBLE,
    LinkMethod VARCHAR,
    LinkReason VARCHAR,

    ConsolidatedDecisionType VARCHAR,
    ConsolidatedTitleKey VARCHAR,
    ConsolidatedRaciTitle VARCHAR,
    ConsolidatedConfidence DOUBLE,
    ConsolidatedReason VARCHAR,
    ConsolidatedSource VARCHAR,

    CreatedAt TIMESTAMP DEFAULT NOW(),
    CreatedBy VARCHAR
);

-- If TimelineTaskToMdrLinks already existed from the first draft, add the new link-level explanation column.
ALTER TABLE my_db.timeline_reconciliation.TimelineTaskToMdrLinks
ADD COLUMN IF NOT EXISTS LinkReason VARCHAR;

COMMENT ON TABLE my_db.timeline_reconciliation.TimelineTaskToMdrLinks IS
'Final business-facing links from Primavera ENG_DOC timeline tasks to historical MDR documents and their consolidated RACI result. One ENG_DOC task may link to multiple MDR documents, represented as multiple rows. This table should contain final judged links, not raw retrieval candidates.';

COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TimelineName IS
'Name of the source Primavera timeline, normally derived from the input XLSX filename. Expected to match historical MDR Mdr_code_name_ref.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ProjectCode IS
'Project code extracted from TimelineName.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TaskRowId IS
'Original row index of the task in the timeline TASK sheet.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TaskCode IS
'Primavera activity/task code when available.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TaskName IS
'Original Primavera task/activity name.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.WbsName IS
'Resolved WBS name associated with the task.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TaskClass IS
'Task classification. Final links are normally created only for ENG_DOC tasks.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TaskClassConfidence IS
'Classifier confidence for TaskClass.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.TaskClassReason IS
'Short explanation of why the task was classified as ENG_DOC or OTHER.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.MdrDocumentTitle IS
'Historical MDR document title linked to the timeline task.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.MdrTitleKey IS
'Normalized key for the linked MDR title.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.LinkRank IS
'Rank of this MDR link among final links for the same timeline task. Lower rank means stronger/preferred association.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.LinkScore IS
'Final confidence or score for the task-to-MDR link, typically assigned by the link evaluation LLM.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.LinkMethod IS
'Method used to create the final link, for example embedding_topk_llm_judge.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.LinkReason IS
'Short explanation of why the timeline task was linked to this MDR document.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ConsolidatedDecisionType IS
'Final business-facing MDR-to-RACI decision type from v_MdrReconciliationResults_Consolidated. Expected value for linked MDR candidates is MATCH.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ConsolidatedTitleKey IS
'Final consolidated RACI TitleKey associated with the linked MDR document.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ConsolidatedRaciTitle IS
'Final consolidated RACI document title associated with the linked MDR document.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ConsolidatedConfidence IS
'Final confidence for the MDR-to-RACI consolidated decision.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ConsolidatedReason IS
'Final explanation for the MDR-to-RACI consolidated decision.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.ConsolidatedSource IS
'Source layer for the consolidated MDR-to-RACI decision, expected values include judge_3_3 and recovery_3_4.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.CreatedAt IS
'Timestamp when this final link row was inserted.';
COMMENT ON COLUMN my_db.timeline_reconciliation.TimelineTaskToMdrLinks.CreatedBy IS
'Script or process that created this final link row.';
